### ISSUE TITLE
create_input script report an wget error in 2023 

### ISSUE THREAD

**Issue by jsjtxietian** [dendibakh/perf-challenge6#6]
Hi thanks for the great challenge.
I find that if one run ./create_input.ps1 directly, wget will tell you it can't find the file to download, because the dump there doesnt contain the DUMPVERSION=20220520 dump by default. 
![image](https://github.com/dendibakh/perf-challenge6/assets/8315986/02107d60-b249-438c-afe2-e6cd2049ac97)
Maybe can update the readme or use DUMPVERSION=latest as default (but the validate depends exactly on this version of wiki).

**Comment by dendibakh** [comment]
I found it in https://dumps.wikimedia.your.org/huwikisource/

**Comment by dendibakh** [comment]
Fixed by https://github.com/dendibakh/perf-challenge6/commit/62ebb0a4667da938e94995bc5531f94dd118e00d
